### ISSUE TITLE
Update binaries and extend documentation

### ISSUE THREAD

**Issue by Dakror** [matpow2/voxie#1]
Hi,
i'm no C or Python dev but only want to use voxie as voxel editor for my game.
But the Windows binaries I dowloaded weren't uptodate and when I tried to build from source I had to download dozens of things that took forever and errors popped up all over.
Same with the Pyton toolchain. I just wanted to run convert.py on my test .vxi file but had again to download several dependencies for it to still crash severely.

Please provide some Docs for Dummys/Users

greetings
Dakror

**Comment by matpow2** [comment]
Hi Dakror

I'll look into this when possible. If you could contribute with a buildbot, that would be great.

**Comment by Dakror** [comment]
Hey,
the CI Platform I use for my projects is [travis.ci.org](http://travis-ci.org)
it has a flexible config but as a drawback their servers don't store build artifacts so you have to transfer them over to another server e.g one under your domain.

**Comment by Dakror** [comment]
Bump

**Comment by Dakror** [comment]
Wow you seem very busy. Going to close this now. It  doesn't matter anymore...

**Comment by matpow2** [comment]
This is still an item on my list.
Of course, contributions are welcome. You could always try and build the editor yourself, then set up a build on Travis. That would be appreciated, at least.

**Comment by Dakror** [comment]
I opened this issue because i don't know how to use the python toolchain. I can't provide stuff either because i simply don't understand / know the setup of the project.

**Comment by Dakror** [comment]
Seams dead
